//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LiteFx.Bases.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LiteFx.Bases.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível excluir o registro. Ele esta relacionado a outros registros..
        /// </summary>
        internal static string NaoFoiPossivelExcluirORegistro {
            get {
                return ResourceManager.GetString("NaoFoiPossivelExcluirORegistro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para criar um BusinessException o parâmetro ValidationResults precisa estar inválido..
        /// </summary>
        internal static string ParaCriarUmaBusinessExceptionOValidationResultsPrecisaEstarInvalido {
            get {
                return ResourceManager.GetString("ParaCriarUmaBusinessExceptionOValidationResultsPrecisaEstarInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not be greater than &apos;{1}&apos;..
        /// </summary>
        internal static string TheFieldXCanNotBeGreaterThanY {
            get {
                return ResourceManager.GetString("TheFieldXCanNotBeGreaterThanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not be less than &apos;{1}&apos;..
        /// </summary>
        internal static string TheFieldXCanNotBeLessThanY {
            get {
                return ResourceManager.GetString("TheFieldXCanNotBeLessThanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not be null..
        /// </summary>
        internal static string TheFieldXCanNotBeNull {
            get {
                return ResourceManager.GetString("TheFieldXCanNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not be null or empty..
        /// </summary>
        internal static string TheFieldXCanNotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("TheFieldXCanNotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not have less than &apos;{1}&apos; characters..
        /// </summary>
        internal static string TheFieldXCanNotHaveLessThanYCharacters {
            get {
                return ResourceManager.GetString("TheFieldXCanNotHaveLessThanYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; can not have more than &apos;{1}&apos; characters..
        /// </summary>
        internal static string TheFieldXCanNotHaveMoreThanYCharacters {
            get {
                return ResourceManager.GetString("TheFieldXCanNotHaveMoreThanYCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be between &apos;{1}&apos; and &apos;{2}&apos;..
        /// </summary>
        internal static string TheFieldXMustBeBetweenYandZ {
            get {
                return ResourceManager.GetString("TheFieldXMustBeBetweenYandZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be different than &apos;{1}&apos;..
        /// </summary>
        internal static string TheFieldXMustBeDifferentThanY {
            get {
                return ResourceManager.GetString("TheFieldXMustBeDifferentThanY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be equals &apos;{1}&apos;..
        /// </summary>
        internal static string TheFieldXMustBeEqualsY {
            get {
                return ResourceManager.GetString("TheFieldXMustBeEqualsY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be null..
        /// </summary>
        internal static string TheFieldXMustBeNull {
            get {
                return ResourceManager.GetString("TheFieldXMustBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must be null or empty..
        /// </summary>
        internal static string TheFieldXMustBeNullOrEmpty {
            get {
                return ResourceManager.GetString("TheFieldXMustBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &apos;{0}&apos; must have &apos;{1}&apos; characters..
        /// </summary>
        internal static string TheFieldXMustHaveYCharacters {
            get {
                return ResourceManager.GetString("TheFieldXMustHaveYCharacters", resourceCulture);
            }
        }
    }
}
